[package]
name = "nerc-keylogger"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = { version = "0.5.3", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
